rLCDC_ENABLE EQU 7
rLCDC_TILE_SELECT EQU 4
rLCDC_SPRITE_ENABLE EQU 1

LY_VBLANK EQU 145

MAP_BORDER EQU 3
SCREEN_WIDTH  EQU 20
SCREEN_HEIGHT EQU 18
BG_MAP_WIDTH EQU 32

JOYPAD_DOWN_BIT EQU 7
JOYPAD_UP_BIT EQU 6
JOYPAD_LEFT_BIT EQU 5
JOYPAD_RIGHT_BIT EQU 4

PLAYER_WALK_COUNT EQU 8

REDRAW_COL EQU 1
REDRAW_ROW EQU 2

DIRECTION_SOUTH EQU 0
DIRECTION_NORTH EQU 1
DIRECTION_EAST EQU 2
DIRECTION_WEST EQU 3

OAM_X_FLIP EQU 5
OAM_Y_FLIP EQU 6
