SCREEN_WIDTH  EQU 20
SCREEN_HEIGHT EQU 18

rLCDC_ENABLE EQU 7
rLCDC_ENABLE_MASK EQU 1 << rLCDC_ENABLE
LY_VBLANK EQU 145

SET_PAL_OVERWORLD            EQU $09
MBC1RomBank         EQU $2000

; width of east/west connections
; height of north/south connections
MAP_BORDER EQU 3
UPDATE_PARTY_MENU_BLK_PACKET EQU $FC

WALK EQU $FE
STAY EQU $FF

DOWN  EQU $D0
UP    EQU $D1
LEFT  EQU $D2
RIGHT EQU $D3
NONE  EQU $FF
